# Generated by Django 5.0.1 on 2024-02-08 17:59

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_employeeprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCommitteeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('office', models.CharField(max_length=255, verbose_name='Кабинет')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Профиль студенческого коммитета',
                'verbose_name_plural': 'Профили студенческого коммитета',
                'ordering': ['position'],
            },
        ),
    ]
