# Generated by Django 5.0.1 on 2024-02-08 18:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_employeeprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcommitteeprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
    ]
