# Generated by Django 5.0.1 on 2024-02-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_studentcommitteeprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='office',
            field=models.TextField(blank=True, null=True, verbose_name='Кабинет'),
        ),
    ]
