# Generated by Django 5.0.1 on 2024-02-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_departmentstaff_department_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentstaff',
            options={'ordering': ['related_profile__full_name'], 'verbose_name': 'Профиль сотрудника департамента', 'verbose_name_plural': 'Профили сотрудников департаментов'},
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Позиция'),
        ),
    ]
