# Generated by Django 5.1.6 on 2025-03-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_departmentstaff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name_en',
            field=models.TextField(null=True, verbose_name='ФИО'),
        ),
    ]
