# Generated by Django 5.1.6 on 2025-04-26 21:45

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_employeeprofile_full_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='job_title_en',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание (англ.)'), blank=True, null=True, size=20, verbose_name='Должности/Звания (англ.)'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='full_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО (англ.)'),
        ),
    ]
