# Generated by Django 5.2.1 on 2025-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_employeeprofile_job_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='office_en',
            field=models.TextField(blank=True, null=True, verbose_name='Кабинет (en)'),
        ),
    ]
