# Generated by Django 5.2.1 on 2025-06-24 09:59

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_employeeprofile_office_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='department_responsibilities_en',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание (en)'), blank=True, null=True, size=20, verbose_name='Должности/Звания (en)'),
        ),
    ]
