# Generated by Django 5.2.13 on 2026-04-13 09:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_alter_departmentstaff_department_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='Номер телефона'), blank=True, null=True, size=10, verbose_name='Номера телефонов'),
        ),
    ]
