# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_employeeprofile_phone_numbers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentstaff',
            options={'ordering': ['related_profile__full_name'], 'verbose_name': 'Сотрудник кафедры', 'verbose_name_plural': 'Сотрудники кафедр'},
        ),
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'ordering': ['full_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='studentcommitteeprofile',
            options={'ordering': ['position'], 'verbose_name': 'Член студенческого комитета', 'verbose_name_plural': 'Студенческий комитет'},
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='department_office_ru',
            field=models.TextField(blank=True, default='Москва, ул. Орджоникидзе, д. 3., каб. ', null=True, verbose_name='Кабинет на кафедре'),
        ),
        migrations.AddField(
            model_name='departmentstaff',
            name='department_responsibilities_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности на кафедре'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name_ru',
            field=models.TextField(null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='job_title_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='office_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочее время'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='working_hours_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочее время'),
        ),
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='job_title_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='job_title_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='office_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='office_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department_office',
            field=models.TextField(blank=True, default='Москва, ул. Орджоникидзе, д. 3., каб. ', null=True, verbose_name='Кабинет на кафедре'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department_office_en',
            field=models.TextField(blank=True, default='Москва, ул. Орджоникидзе, д. 3., каб. ', null=True, verbose_name='Кабинет на кафедре'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department_responsibilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности на кафедре'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department_responsibilities_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности на кафедре'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='related_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_card', to='profiles.employeeprofile', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Электронный адрес'), blank=True, null=True, size=10, verbose_name='Электронные адреса'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='full_name_en',
            field=models.TextField(null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='job_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='job_title_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='office_en',
            field=models.TextField(blank=True, null=True, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_numbers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(verbose_name='Номер телефона'), blank=True, help_text='Добавочный номер указывается через «|»: +74959550952|1234', null=True, size=10, verbose_name='Номера телефонов'),
        ),
        migrations.AlterField(
            model_name='studentcommitteeprofile',
            name='job_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
        migrations.AlterField(
            model_name='studentcommitteeprofile',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
