# Generated by Django 5.2.17 on 2026-10-05 13:59

import apps.education.models
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_translations_and_options'),
        ('education', '0006_rename_models'),
        ('profiles', '0024_translations_and_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalprogram',
            options={'ordering': ['position', 'title'], 'verbose_name': 'Программа ДПО', 'verbose_name_plural': 'Программы ДПО'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['study_level', 'cipher', 'name'], 'verbose_name': 'Образовательная программа', 'verbose_name_plural': 'Образовательные программы'},
        ),
        migrations.AlterModelOptions(
            name='programoffer',
            options={'ordering': ['program', 'study_form'], 'verbose_name': 'Условия приёма', 'verbose_name_plural': 'Условия приёма'},
        ),
        migrations.AlterModelOptions(
            name='studydirection',
            options={'ordering': ['study_level', 'cipher'], 'verbose_name': 'Направление подготовки', 'verbose_name_plural': 'Направления подготовки'},
        ),
        migrations.AlterModelOptions(
            name='translatormodule',
            options={'verbose_name': 'Модуль переводчика', 'verbose_name_plural': 'Модуль переводчика'},
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='information_en',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='information_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть материал на сайте, не удаляя его.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='language_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Язык обучения'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='language_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Язык обучения'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='study_mode_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='study_mode_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название программы'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название программы'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='volume_en',
            field=models.CharField(help_text='Например, «72 академических часа» или «3 зачетные единицы»', max_length=100, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='additionalprogram',
            name='volume_ru',
            field=models.CharField(help_text='Например, «72 академических часа» или «3 зачетные единицы»', max_length=100, null=True, verbose_name='Объем'),
        ),
        migrations.AddField(
            model_name='program',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Описание программы'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть материал на сайте, не удаляя его.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='program',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='programoffer',
            name='note_en',
            field=models.TextField(blank=True, default='', help_text='Если заполнено, у количества бюджетных мест появится сноска «*».', null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='programoffer',
            name='note_ru',
            field=models.TextField(blank=True, default='', help_text='Если заполнено, у количества бюджетных мест появится сноска «*».', null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='studydirection',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='additionalprogram',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость, ₽'),
        ),
        migrations.AlterField(
            model_name='additionalprogram',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_programs', to='academy.department', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='additionalprogram',
            name='volume',
            field=models.CharField(help_text='Например, «72 академических часа» или «3 зачетные единицы»', max_length=100, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='examsubject',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='program',
            name='content',
            field=models.TextField(verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='academy.department', verbose_name='Кафедра / департамент'),
        ),
        migrations.AlterField(
            model_name='program',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], max_length=255, verbose_name='Язык обучения'), default=apps.education.models.default_languages, size=None, verbose_name='Языки обучения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='program',
            name='study_level',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('specialist', 'Специалитет'), ('master', 'Магистратура'), ('postgraduate', 'Аспирантура')], max_length=255, verbose_name='Уровень обучения'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='admission_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на admission.rudn.ru'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='budget_places',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Бюджетных мест'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Если заполнено, у количества бюджетных мест появится сноска «*».', verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='paid_places',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Платных мест'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='price_fifth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='5 год, ₽'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='price_first_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='1 год, ₽'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='price_fourth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='4 год, ₽'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='price_second_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='2 год, ₽'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='price_sixth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='6 год, ₽'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='price_third_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='3 год, ₽'),
        ),
        migrations.AlterField(
            model_name='programoffer',
            name='study_duration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Срок обучения, лет'),
        ),
        migrations.AlterField(
            model_name='studydirection',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studydirection',
            name='study_level',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('specialist', 'Специалитет'), ('master', 'Магистратура'), ('postgraduate', 'Аспирантура')], max_length=255, verbose_name='Уровень обучения'),
        ),
        migrations.AlterField(
            model_name='translatormodule',
            name='contact_employee1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.departmentstaff', verbose_name='Контактное лицо 1'),
        ),
        migrations.AlterField(
            model_name='translatormodule',
            name='contact_employee2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='profiles.departmentstaff', verbose_name='Контактное лицо 2'),
        ),
        migrations.AddConstraint(
            model_name='programoffer',
            constraint=models.UniqueConstraint(fields=('program', 'study_form'), name='education_offer_unique_form'),
        ),
    ]
