# Generated by Django 4.2.6 on 2024-01-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тэг')),
            ],
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
                ('preview_image', models.ImageField(upload_to='news', verbose_name='Фотография')),
                ('content', models.TextField(verbose_name='Информация')),
                ('tags', models.ManyToManyField(to='news.tag', verbose_name='Тэги')),
            ],
        ),
    ]
