# Generated by Django 5.1.6 on 2025-02-25 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsitem_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
    ]
