# Generated by Django 5.2.1 on 2025-06-17 08:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_newsitem_content_en_newsitem_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
    ]
