# Generated by Django 5.2.1 on 2025-07-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_newsitem_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='tags_en',
            field=models.ManyToManyField(blank=True, related_name='news_items_en', to='news.tag', verbose_name='Тэги (eng)'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news_items_ru', to='news.tag', verbose_name='Тэги'),
        ),
    ]
