# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_tags_translation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AddField(
            model_name='newsitem',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть материал на сайте, не удаляя его.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='title_ru',
            field=models.TextField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content',
            field=models.TextField(null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='creation_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Изображение будет обрезано до пропорций 4:3.', null=True, upload_to='news', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.TextField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title_en',
            field=models.TextField(null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Тэг показывается только на тех языковых версиях сайта, где заполнено его название.', max_length=255, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_en',
            field=models.CharField(help_text='Тэг показывается только на тех языковых версиях сайта, где заполнено его название.', max_length=255, null=True, verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(help_text='Тэг показывается только на тех языковых версиях сайта, где заполнено его название.', max_length=255, null=True, verbose_name='Тэг'),
        ),
    ]
