# Generated by Django 4.2.6 on 2023-10-31 20:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('heading', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('sub_heading', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('image', models.ImageField(null=True, upload_to='index_contacts', verbose_name='Фотография')),
                ('phone_numbers', django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'), blank=True, null=True, size=10, verbose_name='Номера телефонов')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Электронный адрес'), blank=True, null=True, size=10, verbose_name='Электронные адреса')),
                ('working_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочее время')),
            ],
            options={
                'verbose_name': 'Контакт на главной странице',
                'verbose_name_plural': 'Контакты на главной странице',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('cipher', models.CharField(max_length=255, verbose_name='Шифр')),
                ('study_level', models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Специалитет', 'Специалитет'), ('Магистратура', 'Магистратура'), ('Аспирантура', 'Аспирантура')], max_length=255, verbose_name='Уровень обучения')),
            ],
            options={
                'verbose_name': 'Профиль направления',
                'verbose_name_plural': 'Профили направления',
            },
        ),
        migrations.CreateModel(
            name='ProfileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('budget_places', models.PositiveIntegerField(verbose_name='Количество бюджетных мест')),
                ('price_first_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость обучения по контракту(1 год)')),
                ('price_second_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость обучения по контракту(2 год)')),
                ('price_third_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость обучения по контракту(3 год)')),
                ('price_fourth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость обучения по контракту(4 год)')),
                ('price_fifth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость обучения по контракту(5 год)')),
                ('price_sixth_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Стоимость обучения по контракту(6 год)')),
                ('minimal_passing_scores', models.JSONField(verbose_name='Минимальные проходные баллы:')),
                ('program_manager', models.CharField(max_length=255, verbose_name='Руководитель программы')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Информация по профилю направления подготовки',
                'verbose_name_plural': 'Информация по профилям направления подготовки',
            },
        ),
        migrations.CreateModel(
            name='StudyDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('study_level', models.CharField(choices=[('Бакалавриат', 'Бакалавриат'), ('Специалитет', 'Специалитет'), ('Магистратура', 'Магистратура'), ('Аспирантура', 'Аспирантура')], max_length=255, verbose_name='Уровень обучения')),
                ('cipher', models.CharField(max_length=255, verbose_name='Шифр')),
                ('profiles', models.ManyToManyField(blank=True, to='pages.profile', verbose_name='Профили')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='extramural_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extramural_details', to='pages.profiledetails', verbose_name='Информация по заочной форме обучения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_time_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_time_details', to='pages.profiledetails', verbose_name='Информация по очной форме обучения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='part_time_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_time_details', to='pages.profiledetails', verbose_name='Информация по очно-заочной форме обучения'),
        ),
    ]
