# Generated by Django 4.2.6 on 2023-10-31 21:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='content',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Информация'),
            preserve_default=False,
        ),
    ]
