# Generated by Django 4.2.6 on 2023-10-31 21:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_profile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Информация'),
        ),
    ]
