# Generated by Django 4.2.6 on 2023-11-01 17:00

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_profile_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcontact',
            name='emails',
            field=django_jsonform.models.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Электронный адрес'), blank=True, null=True, size=10, verbose_name='Электронные адреса'),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='minimal_passing_scores',
            field=django_jsonform.models.fields.JSONField(verbose_name='Минимальные проходные баллы:'),
        ),
    ]
