# Generated by Django 4.2.6 on 2023-11-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_administrationprofiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrationprofiles',
            options={'verbose_name': 'Профиль дирекции', 'verbose_name_plural': 'Профили дирекции'},
        ),
    ]
