# Generated by Django 4.2.6 on 2024-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_administrationprofiles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='sub_header',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
    ]
