# Generated by Django 5.0.1 on 2024-02-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_dissertationcommittee_scientific_specialties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dissertationcommittee',
            options={'ordering': ['cipher'], 'verbose_name': 'Диссертационный совет', 'verbose_name_plural': 'Диссертационные советы'},
        ),
        migrations.AlterModelOptions(
            name='scientificspecialty',
            options={'ordering': ['cipher', 'name'], 'verbose_name': 'Научное направлние', 'verbose_name_plural': 'Научные направления'},
        ),
        migrations.AddField(
            model_name='dissertationcommittee',
            name='deputy',
            field=models.CharField(default=1, max_length=255, verbose_name='Заместитель председателя'),
            preserve_default=False,
        ),
    ]
