# Generated by Django 5.0.1 on 2024-02-08 14:36

import django_jsonform.models.fields
import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_profile_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AddField(
            model_name='profile',
            name='language_fields',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский'), ('Русский и английский', 'Русский и английский')], max_length=255, verbose_name='Язык обучения'), default=pages.models.Profile.get_languages, size=None),
        ),
    ]
