# Generated by Django 5.0.1 on 2024-02-09 23:13

import django.db.models.deletion
import django_jsonform.models.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_remove_profile_faculty_profile_faculty_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('prefix', models.CharField(blank=True, help_text='Для удобства поиска в админке', max_length=255, null=True, verbose_name='Префикс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment', verbose_name='Фотография')),
                ('purpose', models.TextField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['prefix', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartnerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование организации')),
                ('prefix', models.CharField(blank=True, help_text='Для удобства поиска в админке', max_length=255, null=True, verbose_name='Префикс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment', verbose_name='Фотография')),
                ('collaboration_direction', models.TextField(verbose_name='Предмет сотрудничества')),
                ('result', models.TextField(verbose_name='Результат сотрудничества')),
                ('about', models.TextField(verbose_name='О партнёре')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['prefix', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScientificCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('address', models.CharField(default='115419, Москва, улица Орджоникидзе, 3', max_length=255, verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта')),
                ('brief_description', models.TextField(verbose_name='Краткое описание')),
                ('scientists', django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Команда ученых')),
                ('scientific_directions', django_jsonform.models.fields.ArrayField(base_field=models.TextField(verbose_name='Научные направления'), size=None)),
                ('achievements', django_jsonform.models.fields.ArrayField(base_field=models.TextField(verbose_name='Достижения / результаты проектов-исследований'), size=None)),
                ('equipment', models.ManyToManyField(to='pages.equipmentdata', verbose_name='Оборудование')),
                ('faculty_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_info_for_scientific_centers', to='pages.departmentinfo', verbose_name='Департамент/Кафедра')),
                ('partners', models.ManyToManyField(to='pages.partnerdata', verbose_name='Сотрудничество, партнеры')),
            ],
        ),
    ]
