# Generated by Django 5.0.1 on 2024-02-09 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_scientificcenters_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerdata',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
