# Generated by Django 5.0.1 on 2024-02-09 23:57

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_alter_scientificcenters_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificcenters',
            name='achievements',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(verbose_name='Достижения / результаты проектов-исследований'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scientificcenters',
            name='brief_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='scientificcenters',
            name='scientific_directions',
            field=django_jsonform.models.fields.ArrayField(base_field=models.TextField(verbose_name='Научные направления'), blank=True, null=True, size=None),
        ),
    ]
