# Generated by Django 5.0.1 on 2024-02-10 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_scientificcenters_achievements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificcenters',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Научный центр', 'verbose_name_plural': 'Научные центры'},
        ),
    ]
