# Generated by Django 5.0.1 on 2024-02-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_alter_scientificcenters_options'),
        ('profiles', '0013_departmentstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinfo',
            name='staff',
            field=models.ManyToManyField(blank=True, to='profiles.departmentstaff', verbose_name='Сотрудники департамента'),
        ),
    ]
