# Generated by Django 5.2.1 on 2025-06-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_alter_profiledetails_study_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='study_duration',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Продолжительность обучения'),
        ),
    ]
