# Generated by Django 5.2.1 on 2025-06-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0051_alter_profiledetails_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentinfo',
            options={'ordering': ['position'], 'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='job_title',
            field=models.CharField(choices=[('director', 'Директор департамента'), ('head', 'Заведующий кафедры')], default='director', max_length=32, verbose_name='Должность руководителя'),
        ),
    ]
