# Generated by Django 5.2.1 on 2025-06-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0052_alter_departmentinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='image_full_en',
            field=models.ImageField(blank=True, null=True, upload_to='main_slider_full_en', verbose_name='Фотография полноразмерная (en)'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image_mobile_en',
            field=models.ImageField(blank=True, null=True, upload_to='main_slider_mobile_en', verbose_name='Фотография мобильная (en)'),
        ),
    ]
