# Generated by Django 5.2.1 on 2025-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_mainslider_image_full_en_mainslider_image_mobile_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinfo',
            name='job_title',
            field=models.CharField(choices=[('director', 'Директор департамента'), ('head', 'Заведующий кафедрой')], default='director', max_length=32, verbose_name='Должность руководителя'),
        ),
    ]
