# Generated by Django 5.2.1 on 2025-07-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0055_alter_profiledetails_note'),
        ('profiles', '0022_alter_departmentstaff_department_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_employee1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_employee1', to='profiles.departmentstaff', verbose_name='Контактное лицо 1')),
                ('contact_employee2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_employee2', to='profiles.departmentstaff', verbose_name='Контактное лицо 2')),
            ],
            options={
                'verbose_name': 'Дополнительное образование',
                'verbose_name_plural': 'Дополнительное образование',
            },
        ),
    ]
