# Generated by Django 5.2.1 on 2025-08-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_additionaleducationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaleducationitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
