# Generated by Django 5.2.17 on 2026-10-05 14:00

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_move_models_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть материал на сайте, не удаляя его.', verbose_name='Опубликовано')),
                ('path', models.CharField(help_text='Например: science/new-lab → https://academy.rudn.ru/science/new-lab', max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9][a-z0-9_\\-/]*[a-z0-9]$|^[a-z0-9]$', 'Используйте латиницу в нижнем регистре, цифры, «-», «_» и «/» (без «/» в начале и конце).')], verbose_name='Адрес страницы')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, default='', verbose_name='Содержимое')),
                ('content_ru', models.TextField(blank=True, default='', null=True, verbose_name='Содержимое')),
                ('content_en', models.TextField(blank=True, default='', null=True, verbose_name='Содержимое')),
                ('seo_description', models.CharField(blank=True, default='', max_length=300, verbose_name='Описание для поисковиков')),
                ('seo_description_ru', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Описание для поисковиков')),
                ('seo_description_en', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Описание для поисковиков')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменена')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ['path'],
            },
        ),
        migrations.AlterModelOptions(
            name='indexcontact',
            options={'ordering': ['position'], 'verbose_name': 'Контакт на главной', 'verbose_name_plural': 'Контакты на главной'},
        ),
        migrations.AlterModelOptions(
            name='mainslider',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Слайд на главной', 'verbose_name_plural': 'Слайдер на главной'},
        ),
        migrations.AddField(
            model_name='indexcontact',
            name='heading_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='indexcontact',
            name='heading_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='indexcontact',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='indexcontact',
            name='location_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='indexcontact',
            name='sub_heading_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='indexcontact',
            name='sub_heading_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AddField(
            model_name='indexcontact',
            name='working_hours_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочее время'),
        ),
        migrations.AddField(
            model_name='indexcontact',
            name='working_hours_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочее время'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image_full_ru',
            field=models.ImageField(blank=True, help_text='Широкий баннер для экранов от 960px.', null=True, upload_to='main_slider_full', verbose_name='Изображение для компьютера'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='image_mobile_ru',
            field=models.ImageField(blank=True, null=True, upload_to='main_slider_mobile', verbose_name='Изображение для телефона'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть материал на сайте, не удаляя его.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='mainslider',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indexcontact',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Электронный адрес'), blank=True, null=True, size=10, verbose_name='Электронные адреса'),
        ),
        migrations.AlterField(
            model_name='indexcontact',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='indexcontact',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image_full',
            field=models.ImageField(blank=True, help_text='Широкий баннер для экранов от 960px.', null=True, upload_to='main_slider_full', verbose_name='Изображение для компьютера'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image_full_en',
            field=models.ImageField(blank=True, help_text='Широкий баннер для экранов от 960px.', null=True, upload_to='main_slider_full', verbose_name='Изображение для компьютера'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='main_slider_mobile', verbose_name='Изображение для телефона'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='image_mobile_en',
            field=models.ImageField(blank=True, null=True, upload_to='main_slider_mobile', verbose_name='Изображение для телефона'),
        ),
        migrations.AlterField(
            model_name='mainslider',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
