global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: "/prometheus-PROMETHEUS_URL_SUFFIX/metrics"
    static_configs:
      - targets: ["127.0.0.1:8001"]
