# Generated by Django 5.0.1 on 2024-05-16 08:54

import ckeditor_uploader.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_mainslider_url'),
        ('seminars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name='Имя')),
                ('last_name', models.TextField(verbose_name='Фамилия')),
                ('middle_name', models.TextField(blank=True, null=True, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seminar_speakers', verbose_name='Фотография')),
                ('job_title', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание + Название организации'), blank=True, null=True, size=20, verbose_name='Должности/Звания')),
                ('academic_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученое звание')),
                ('academic_degree', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученая степень')),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Биография')),
            ],
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='date',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='holding_place',
        ),
        migrations.RemoveField(
            model_name='seminar',
            name='responsible_person',
        ),
        migrations.AlterField(
            model_name='seminar',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_seminar', to='pages.departmentinfo', verbose_name='Департамент'),
        ),
        migrations.CreateModel(
            name='SeminarReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('time_start', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('time_end', models.TimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('annotation', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Аннотация')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_report', to='seminars.seminarspeaker', verbose_name='Докладчик')),
            ],
        ),
    ]
