# Generated by Django 5.0.1 on 2024-05-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0002_seminarspeaker_remove_seminar_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminarreport',
            options={'verbose_name': 'Доклад', 'verbose_name_plural': 'Доклады'},
        ),
        migrations.AlterModelOptions(
            name='seminarspeaker',
            options={'verbose_name': 'Докладчик', 'verbose_name_plural': 'Докладчики'},
        ),
        migrations.AddField(
            model_name='seminar',
            name='reports',
            field=models.ManyToManyField(blank=True, to='seminars.seminarreport', verbose_name='Доклады'),
        ),
    ]
