# Generated by Django 5.0.1 on 2024-05-16 17:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0004_seminarreport_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='пвыщздэалпыавзжлдьларпвзджлрьпвджалртьпавдлртьпавдэрьпавдэлрьпадэрьпалдзрьпа\nвпыалщтывапщдолжтрпваощдтрапвощждртапв', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
