# Generated by Django 5.0.1 on 2024-05-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0006_seminar_chair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarspeaker',
            name='image',
            field=models.ImageField(blank=True, default='profile_default.png', null=True, upload_to='seminar_speakers', verbose_name='Фотография'),
        ),
    ]
