# Generated by Django 5.0.1 on 2024-05-17 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_alter_seminarspeaker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarspeaker',
            name='image',
            field=models.ImageField(blank=True, default='uploads/profile_default.png', null=True, upload_to='seminar_speakers', verbose_name='Фотография'),
        ),
    ]
