# Generated by Django 5.0.1 on 2024-05-20 15:12

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0007_alter_seminarspeaker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarreport',
            name='annotation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seminar_speakers', verbose_name='Фотография'),
        ),
    ]
