# Generated by Django 5.0.1 on 2024-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0008_alter_seminarspeaker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarspeaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seminar_speakers', verbose_name='Фотография'),
        ),
    ]
