# Generated by Django 5.1.1 on 2024-09-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0012_remove_seminar_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='seminar_images/'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='position',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
