# Generated by Django 5.1.6 on 2025-04-28 12:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0014_alter_seminar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание (англ.)'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Название (англ.)'),
        ),
        migrations.AddField(
            model_name='seminarreport',
            name='annotation_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Аннотация (англ.)'),
        ),
        migrations.AddField(
            model_name='seminarreport',
            name='name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Название (англ.)'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='bio_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Биография (англ.)'),
        ),
    ]
