# Generated by Django 5.2.1 on 2025-06-17 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_employeeprofile_job_title_en_and_more'),
        ('seminars', '0015_seminar_description_en_seminar_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='organizer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_organizer', to='profiles.employeeprofile', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='chair1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seminar_chairman', to='profiles.employeeprofile', verbose_name='Председатель'),
        ),
    ]
