# Generated by Django 5.2.1 on 2025-06-19 14:50

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0017_seminarreport_online_meeting_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarreport',
            name='presentation_file',
            field=models.FileField(blank=True, null=True, upload_to='presentations/%Y/%m/', verbose_name='Presentation (PDF / PPT)'),
        ),
        migrations.AddField(
            model_name='seminarreport',
            name='video_recording',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Video recording URL'),
        ),
    ]
