# Generated by Django 5.2.1 on 2025-11-06 11:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0023_populate_report_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarreport',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID for URL'),
        ),
    ]
