# Generated by Django 5.2.1 on 2025-11-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0024_alter_seminarreport_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarspeaker',
            name='first_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Имя (EN)'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='last_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Фамилия (EN)'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='middle_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Отчество (EN)'),
        ),
    ]
