# Generated by Django 4.2.28 on 2026-03-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0027_alter_seminarspeaker_academic_degree_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarreport',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видеозапись (файл)'),
        ),
    ]
