# Generated by Django 4.2.6 on 2024-01-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Название'),
        ),
    ]
