# Generated by Django 4.2.6 on 2024-01-26 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
