# Generated by Django 4.2.6 on 2024-01-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_newsitem_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='news', verbose_name='Фотография'),
        ),
    ]
