# Generated by Django 5.0.1 on 2024-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsitem_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='title_en',
            field=models.TextField(default='', verbose_name='Название на английском'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(default='', max_length=255, verbose_name='Тэг на английском'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
