# Generated by Django 5.0.1 on 2024-05-31 20:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newsitem_title_en_tag_name_en_alter_newsitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация на английском'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name='Название на английском'),
        ),
    ]
