# Generated by Django 5.2.1 on 2025-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_newsitem_content_alter_newsitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='title_en',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
