# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_restructure'),
        ('profiles', '0024_translations_and_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrationmember',
            options={'ordering': ['position', 'employee__full_name'], 'verbose_name': 'Член дирекции', 'verbose_name_plural': 'Дирекция'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['position'], 'verbose_name': 'Кафедра / департамент', 'verbose_name_plural': 'Кафедры и департаменты'},
        ),
        migrations.AddField(
            model_name='department',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Информация о кафедре'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='administrationmember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administration_memberships', to='profiles.employeeprofile', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='administrationmember',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for_departments', to='profiles.departmentstaff', verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='profiles.departmentstaff', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='department',
            name='info',
            field=models.TextField(verbose_name='Информация о кафедре'),
        ),
        migrations.AlterField(
            model_name='department',
            name='info_en',
            field=models.TextField(null=True, verbose_name='Информация о кафедре'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='department',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='department',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='departments', to='profiles.departmentstaff', verbose_name='Сотрудники'),
        ),
    ]
