# Generated by Django 5.2.17 on 2026-10-05 14:00

import apps.media_library.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='media_library.mediafolder', verbose_name='Родительская папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['parent__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.media_library.models.upload_to, verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('alt', models.CharField(blank=True, help_text='Описание изображения для незрячих и поисковиков.', max_length=255, verbose_name='Альтернативный текст')),
                ('alt_ru', models.CharField(blank=True, help_text='Описание изображения для незрячих и поисковиков.', max_length=255, null=True, verbose_name='Альтернативный текст')),
                ('alt_en', models.CharField(blank=True, help_text='Описание изображения для незрячих и поисковиков.', max_length=255, null=True, verbose_name='Альтернативный текст')),
                ('kind', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ'), ('archive', 'Архив'), ('other', 'Другое')], db_index=True, default='other', max_length=16, verbose_name='Тип')),
                ('mime_type', models.CharField(blank=True, max_length=127, verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер, байт')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Загружен')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='media_library.mediafolder', verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='mediafolder',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='media_folder_unique_name'),
        ),
    ]
