# Generated by Django 4.2.6 on 2023-11-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_profile_employeeprofile'),
        ('pages', '0004_alter_indexcontact_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrationProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile', verbose_name='Сотрудник')),
            ],
        ),
    ]
