# Generated by Django 5.0.1 on 2024-01-31 20:17

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_profiledetails_paid_places_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='job_title',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
    ]
