# Generated by Django 5.0.1 on 2024-01-31 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_profiledetails_job_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrationprofiles',
            options={'ordering': ['position', 'employee__full_name'], 'verbose_name': 'Профиль дирекции', 'verbose_name_plural': 'Профили дирекции'},
        ),
    ]
