# Generated by Django 5.0.1 on 2024-02-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_administrationprofiles_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='extramural_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extramural_details', to='pages.profiledetails', verbose_name='Информация по заочной форме обучения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_time_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='full_time_details', to='pages.profiledetails', verbose_name='Информация по очной форме обучения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='part_time_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_time_details', to='pages.profiledetails', verbose_name='Информация по очно-заочной форме обучения'),
        ),
    ]
