# Generated by Django 5.0.1 on 2024-02-07 13:43

import django_jsonform.models.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_profile_extramural_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(max_length=255, verbose_name='Шифр')),
                ('name', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='DissertationCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher', models.CharField(max_length=255, verbose_name='Шифр совета')),
                ('orgnization', models.CharField(default='Российский университет дружбы народов', max_length=255, verbose_name='Организация')),
                ('faculty', models.CharField(default='Инженерная академия', max_length=255, verbose_name='Факультет')),
                ('address', models.CharField(default='улица Орджоникидзе, 3, Москва, 115419', max_length=255, verbose_name='Адрес')),
                ('chairman', models.CharField(max_length=255, verbose_name='Председатель')),
                ('secretary', models.CharField(max_length=255, verbose_name='Секретарь')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта')),
                ('composition', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Участник диссовета'), blank=True, null=True, size=20, verbose_name='Cостав диссовета')),
                ('scientific_specialties', models.ManyToManyField(blank=True, to='pages.profile', verbose_name='Научные специальности')),
            ],
        ),
    ]
