# Generated by Django 5.0.1 on 2024-02-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_scientificspecialty_dissertationcommittee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='scientific_specialties',
            field=models.ManyToManyField(blank=True, to='pages.scientificspecialty', verbose_name='Научные специальности'),
        ),
    ]
