# Generated by Django 5.0.1 on 2024-02-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_dissertationcommittee_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dissertationcommittee',
            old_name='orgnization',
            new_name='organization',
        ),
    ]
