# Generated by Django 5.0.1 on 2024-02-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_rename_orgnization_dissertationcommittee_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='address',
            field=models.CharField(default='115419, Москва, улица Орджоникидзе, 3', max_length=255, verbose_name='Адрес'),
        ),
    ]
