# Generated by Django 5.0.1 on 2024-02-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_alter_dissertationcommittee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский'), ('Русский и английский', 'Русский и английский')], default='Русский', max_length=255, verbose_name='Язык обучения'),
        ),
    ]
