# Generated by Django 5.0.1 on 2024-02-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_remove_profile_language_profile_language_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, default='Департамент механики и процессов управления', help_text='Полностью, например: Департамент механики и процессов управления', max_length=255, null=True, verbose_name='Кафедра/Факультет/Департамен'),
        ),
    ]
