# Generated by Django 5.0.1 on 2024-02-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_profile_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='study_duration',
            field=models.IntegerField(default=4, verbose_name='Длительность обучения'),
        ),
    ]
