# Generated by Django 5.0.1 on 2024-02-08 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_profile_study_duration'),
        ('profiles', '0011_studentcommitteeprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название департамента')),
                ('info', models.TextField(verbose_name='Информация о департаменте')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile', verbose_name='Руководитель')),
            ],
        ),
    ]
