# Generated by Django 5.0.1 on 2024-02-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_departmentinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinfo',
            name='job_title',
            field=models.CharField(choices=[('Директор департамента', 'Директор департамента'), ('Заведующий кафедры', 'Заведующий кафедры')], default='Директор департамента', max_length=255, verbose_name='Должность руководителя'),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='name',
            field=models.TextField(verbose_name='Название департамента'),
        ),
    ]
