# Generated by Django 5.0.1 on 2024-02-09 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_departmentinfo_job_title_alter_departmentinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='faculty',
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_info', to='pages.departmentinfo', verbose_name='Департамент/Кафедра'),
        ),
    ]
