# Generated by Django 5.0.1 on 2024-02-09 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_equipmentdata_partnerdata_scientificcenters'),
        ('profiles', '0012_alter_employeeprofile_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificcenters',
            options={'ordering': ['name'], 'verbose_name': 'Научный центр', 'verbose_name_plural': 'Научные центры'},
        ),
        migrations.AddField(
            model_name='scientificcenters',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.employeeprofile', verbose_name='Руководитель'),
        ),
    ]
