# Generated by Django 5.0.1 on 2024-02-10 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_departmentinfo_staff'),
        ('profiles', '0016_alter_departmentstaff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinfo',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to='profiles.departmentstaff', verbose_name='Руководитель'),
        ),
    ]
