# Generated by Django 5.0.1 on 2024-02-11 17:23

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_alter_departmentinfo_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledetails',
            name='minimal_passing_scores',
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='admission_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ссылка на admission.rudn'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='minimal_passing_scores_budget',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Минимальные проходные баллы на бюджет:'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='minimal_passing_scores_contract',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True, verbose_name='Минимальные проходные баллы на контракт:'),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='study_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность обучения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cipher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Шифр'),
        ),
    ]
