# Generated by Django 5.0.1 on 2024-02-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_alter_profile_study_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='study_duration',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='program_manager',
        ),
        migrations.RemoveField(
            model_name='profiledetails',
            name='sub_header',
        ),
    ]
