# Generated by Django 5.0.1 on 2024-02-12 08:42

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_remove_profile_study_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificcenters',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='scientificcenters',
            name='address',
        ),
        migrations.RemoveField(
            model_name='scientificcenters',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scientificcenters',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='scientificcenters',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='scientificcenters',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='scientificcenters',
            name='scientific_directions',
        ),
        migrations.RemoveField(
            model_name='scientificcenters',
            name='scientists',
        ),
        migrations.AddField(
            model_name='scientificcenters',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
        migrations.AddField(
            model_name='scientificcenters',
            name='email_fields',
            field=django_jsonform.models.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Электронный адрес'), blank=True, null=True, size=10, verbose_name='Электронные адреса'),
        ),
        migrations.AddField(
            model_name='scientificcenters',
            name='field_name',
            field=models.TextField(default='new', verbose_name='Сфера деятельности'),
            preserve_default=False,
        ),
    ]
