# Generated by Django 5.0.1 on 2024-02-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_remove_scientificcenters_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificcenters',
            name='field_name',
            field=models.TextField(blank=True, null=True, verbose_name='Сфера деятельности'),
        ),
    ]
