# Generated by Django 5.0.1 on 2024-02-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_alter_scientificcenters_field_name'),
        ('profiles', '0016_alter_departmentstaff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinfo',
            name='contact_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_employee', to='profiles.departmentstaff', verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_of_department', to='profiles.departmentstaff', verbose_name='Руководитель'),
        ),
    ]
