# Generated by Django 5.0.1 on 2024-02-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_scientificcenters_page_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('image_full', models.ImageField(blank=True, null=True, upload_to='main_slider_full', verbose_name='Фотография полноразмерная')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='main_slider_mobile', verbose_name='Фотография мобильная')),
            ],
            options={
                'verbose_name': 'Картинка главного слайдера',
                'verbose_name_plural': 'Картинки главного слайдера',
                'ordering': ['position', 'name'],
            },
        ),
    ]
