# Generated by Django 5.1.6 on 2025-04-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_mainslider_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentinfo',
            name='info_en',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о департаменте (англ.)'),
        ),
        migrations.AddField(
            model_name='departmentinfo',
            name='name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Название департамента (англ.)'),
        ),
    ]
