# Generated by Django 5.1.6 on 2025-04-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_departmentinfo_info_en_departmentinfo_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificcenters',
            name='brief_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание (англ.)'),
        ),
        migrations.AddField(
            model_name='scientificcenters',
            name='field_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Сфера деятельности (англ.)'),
        ),
        migrations.AddField(
            model_name='scientificcenters',
            name='name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Название (англ.)'),
        ),
    ]
