# Generated by Django 5.2.1 on 2025-06-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_profile_content_en_profile_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='study_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Продолжительность обучения'),
        ),
    ]
