# Generated by Django 5.2.1 on 2025-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0049_alter_profiledetails_study_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='note',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Примечание'),
        ),
    ]
