# Generated by Django 5.2.1 on 2025-06-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0050_profiledetails_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledetails',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='Примечание'),
        ),
    ]
