# Generated by Django 5.2.1 on 2025-08-15 12:25

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0056_additionaleducation'),
        ('profiles', '0022_alter_departmentstaff_department_office_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalEducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('volume', models.CharField(help_text="Например, '72 академических часа' или '3 зачетные единицы'", max_length=100, verbose_name='Объем')),
                ('study_mode', models.CharField(max_length=100, verbose_name='Форма обучения')),
                ('language', models.CharField(max_length=100, verbose_name='Язык обучения')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Стоимость в рублях', max_digits=10, verbose_name='Стоимость')),
                ('information', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Дополнительная информация')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_for_programs', to='profiles.departmentstaff', verbose_name='Контактное лицо')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.departmentinfo', verbose_name='Кафедра')),
                ('program_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_programs', to='profiles.departmentstaff', verbose_name='Руководитель программы')),
            ],
            options={
                'verbose_name': 'Программа ДПО',
                'verbose_name_plural': 'Программы ДПО',
            },
        ),
    ]
