# Generated by Django 4.2.6 on 2023-11-13 11:19

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('department', models.TextField(verbose_name='БУП')),
                ('date', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Даты проведения')),
                ('holding_place', models.TextField(verbose_name='Место проведения')),
                ('responsible_person', models.TextField(verbose_name='Ответственный за проведение(ФИО)')),
            ],
            options={
                'verbose_name': 'Научный семинар',
                'verbose_name_plural': 'Научные семинары',
            },
        ),
    ]
