# Generated by Django 5.0.1 on 2024-05-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0005_seminar_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='chair',
            field=models.TextField(default='Председатель', verbose_name='Председатель'),
            preserve_default=False,
        ),
    ]
