# Generated by Django 5.0.1 on 2024-06-22 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_departmentstaff_options_and_more'),
        ('seminars', '0008_alter_seminarreport_annotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='chair1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile', verbose_name='Председатель'),
        ),
    ]
