# Generated by Django 5.0.1 on 2024-06-23 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0009_seminar_chair1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarreport',
            name='speaker',
            field=models.ForeignKey(blank=True, default='profile_default.png', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_report', to='seminars.seminarspeaker', verbose_name='Докладчик'),
        ),
    ]
