# Generated by Django 5.0.1 on 2024-06-23 18:41

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0010_alter_seminarreport_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
