# Generated by Django 5.0.1 on 2024-06-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0011_alter_seminar_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='chair',
        ),
    ]
