# Generated by Django 5.1.6 on 2025-02-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0013_seminar_image_seminar_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, default='default_seminar.jpg', null=True, upload_to='seminar_images/'),
        ),
    ]
