# Generated by Django 5.2.1 on 2025-06-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0016_seminar_organizer1_alter_seminar_chair1'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarreport',
            name='online_meeting_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на онлайн-конференцию'),
        ),
    ]
