# Generated by Django 5.2.1 on 2025-06-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0018_seminarreport_presentation_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarreport',
            name='presentation_file',
            field=models.TextField(blank=True, null=True, verbose_name='Presentation (PDF / PPT)'),
        ),
    ]
