# Generated by Django 5.2.1 on 2025-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0021_alter_seminarreport_presentation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarreport',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID for URL'),
        ),
    ]
