# Generated by Django 5.2.1 on 2025-11-06 11:22

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    SeminarReport = apps.get_model('seminars', 'SeminarReport')
    for row in SeminarReport.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0022_seminarreport_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]