# Generated by Django 5.2.1 on 2025-11-12 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0025_seminarspeaker_first_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminarspeaker',
            name='academic_degree_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='academic_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученое звание'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='job_title_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание + Название организации'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
    ]
