# Generated by Django 5.2.1 on 2025-11-12 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminars', '0026_seminarspeaker_academic_degree_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminarspeaker',
            name='academic_degree_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученая степень (ENG)'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='academic_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученое звание (ENG)'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='job_title_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание + Название организации (ENG)'), blank=True, null=True, size=20, verbose_name='Должности/Звания (ENG)'),
        ),
    ]
