# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_translations_and_options'),
        ('profiles', '0024_translations_and_options'),
        ('seminars', '0030_restructure_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'ordering': ['position', 'name'], 'verbose_name': 'Научный семинар', 'verbose_name_plural': 'Научные семинары'},
        ),
        migrations.AlterModelOptions(
            name='seminarreport',
            options={'ordering': ['-date_start', 'week'], 'verbose_name': 'Доклад', 'verbose_name_plural': 'Доклады'},
        ),
        migrations.AlterModelOptions(
            name='seminarspeaker',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Докладчик', 'verbose_name_plural': 'Докладчики'},
        ),
        migrations.AddField(
            model_name='seminar',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть материал на сайте, не удаляя его.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='seminar',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='seminarreport',
            name='annotation_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Аннотация'),
        ),
        migrations.AddField(
            model_name='seminarreport',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Тема доклада'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='academic_degree_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='academic_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученое звание'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='first_name_ru',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='job_title_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание + Название организации'), blank=True, null=True, size=20, verbose_name='Должности и организации'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='last_name_ru',
            field=models.TextField(null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='seminarspeaker',
            name='middle_name_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='chair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_seminars', to='profiles.employeeprofile', verbose_name='Председатель'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminars', to='academy.department', verbose_name='Кафедра / департамент'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='image',
            field=models.ImageField(blank=True, default='default_seminar.jpg', null=True, upload_to='seminar_images/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_seminars', to='profiles.employeeprofile', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='annotation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='name',
            field=models.TextField(verbose_name='Тема доклада'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Тема доклада'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='presentation_file',
            field=models.TextField(blank=True, help_text='Презентация и другие материалы: загрузите файл через кнопку изображения/ссылки в редакторе.', null=True, verbose_name='Материалы доклада'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='seminars.seminarspeaker', verbose_name='Докладчик'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='time_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID для ссылки'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='video_recording',
            field=models.URLField(blank=True, null=True, verbose_name='Видеозапись (ссылка)'),
        ),
        migrations.AlterField(
            model_name='seminarreport',
            name='week',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Неделя'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='academic_degree_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='academic_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ученое звание'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='first_name_en',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='job_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание + Название организации'), blank=True, null=True, size=20, verbose_name='Должности и организации'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='job_title_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание + Название организации'), blank=True, null=True, size=20, verbose_name='Должности и организации'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='last_name_en',
            field=models.TextField(null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='seminarspeaker',
            name='middle_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Отчество'),
        ),
    ]
