# Generated by Django 4.2.6 on 2024-01-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDaysFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents', verbose_name='Файл')),
                ('type', models.CharField(choices=[('Презентация', 'Презентация'), ('Фотография', 'Фотография')], max_length=255, verbose_name='Тип файла')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='applicantscisnormativedocument',
            options={'verbose_name': 'Абитуриенты ссылка на нормативный документ для граждан российской федерации и стран СНГ', 'verbose_name_plural': 'Абитуриенты ссылки на нормативные документы для граждан российской федерации и стран СНГ'},
        ),
        migrations.AlterModelOptions(
            name='applicantsforeignnormativedocument',
            options={'verbose_name': 'Абитуриенты ссылка на нормативный документ для иностранных граждан', 'verbose_name_plural': 'Абитуриенты ссылки на нормативные документы для иностранных граждан'},
        ),
    ]
