# Generated by Django 4.2.6 on 2024-01-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_opendaysfiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='documents', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Образец заявления',
                'verbose_name_plural': 'Студенты образцы заявлений',
            },
        ),
        migrations.AlterModelOptions(
            name='applicantscisnormativedocument',
            options={'verbose_name': 'Ссылка на нормативный документ для граждан российской федерации и стран СНГ', 'verbose_name_plural': 'Абитуриенты ссылки на нормативные документы для граждан российской федерации и стран СНГ'},
        ),
        migrations.AlterModelOptions(
            name='applicantsforeignnormativedocument',
            options={'verbose_name': 'Ссылка на нормативный документ для иностранных граждан', 'verbose_name_plural': 'Абитуриенты ссылки на нормативные документы для иностранных граждан'},
        ),
        migrations.AlterModelOptions(
            name='opendaysfiles',
            options={'verbose_name': 'Файл для дня открытых дверей', 'verbose_name_plural': 'Абитуриенты файлы для дня открытых дверей'},
        ),
    ]
