# Generated by Django 5.0.1 on 2024-02-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_applicantscisnormativedocument_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentsapplications',
            options={'ordering': ['position'], 'verbose_name': 'Образец заявления', 'verbose_name_plural': 'Студенты образцы заявлений'},
        ),
    ]
