# Generated by Django 5.2.17 on 2026-10-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(help_text='Для английской версии сайта можно загрузить отдельный файл; если его нет — показывается русский.', max_length=255, upload_to='documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_en',
            field=models.FileField(help_text='Для английской версии сайта можно загрузить отдельный файл; если его нет — показывается русский.', max_length=255, null=True, upload_to='documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_ru',
            field=models.FileField(help_text='Для английской версии сайта можно загрузить отдельный файл; если его нет — показывается русский.', max_length=255, null=True, upload_to='documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
