# Generated by Django 4.2.6 on 2023-11-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.TextField(default=1, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
