# Generated by Django 4.2.6 on 2023-11-01 17:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Информация'),
        ),
    ]
