# Generated by Django 4.2.6 on 2023-11-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='EmployeeProfile',
        ),
    ]
