# Generated by Django 5.0.1 on 2024-02-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_studentcommitteeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_default.png', upload_to='student_committee_profiles', verbose_name='Фотография'),
        ),
    ]
