# Generated by Django 5.0.1 on 2024-02-08 18:02

import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_studentcommitteeprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': 'Профиль сотрудника', 'verbose_name_plural': 'Профили сотрудников'},
        ),
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='job_title',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
    ]
