# Generated by Django 5.0.1 on 2024-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_studentcommitteeprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcommitteeprofile',
            name='email',
            field=models.EmailField(default=1, max_length=255, verbose_name='Электронный адрес'),
            preserve_default=False,
        ),
    ]
