# Generated by Django 5.0.1 on 2024-02-10 22:17

import django.db.models.deletion
import django_jsonform.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_alter_employeeprofile_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_responsibilities', django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания')),
                ('related_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.employeeprofile', verbose_name='Связанный профиль сотрудника')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника департамента',
                'verbose_name_plural': 'Профили сотрудников департаментов',
            },
        ),
    ]
