# Generated by Django 5.0.1 on 2024-02-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_departmentstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='department_office',
            field=models.TextField(blank=True, null=True, verbose_name='Кабинет департамента'),
        ),
    ]
