# Generated by Django 5.0.1 on 2024-02-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_departmentstaff_department_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstaff',
            name='department_office',
            field=models.TextField(blank=True, default='Москва, ул. Орджоникидзе, д. 3., каб', null=True, verbose_name='Кабинет департамента'),
        ),
    ]
