# Generated by Django 5.0.1 on 2024-06-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_alter_departmentstaff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО'),
        ),
    ]
