# Generated by Django 5.0.1 on 2024-06-17 13:47

import django.contrib.postgres.fields
import django_jsonform.models.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_employeeprofile_full_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='emails_en',
            field=django_jsonform.models.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Электронный адрес'), blank=True, null=True, size=10, verbose_name='Электронные адреса'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='job_title_en',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Должность/Звание'), blank=True, null=True, size=20, verbose_name='Должности/Звания'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='office_en',
            field=models.TextField(blank=True, null=True, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone_numbers_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона'), blank=True, null=True, size=10, verbose_name='Номера телефонов'),
        ),
    ]
