# Generated by Django 5.0.1 on 2024-06-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_employeeprofile_emails_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='emails_en',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='office_en',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='phone_numbers_en',
        ),
    ]
