# Generated by Django 5.2.1 on 2025-06-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_departmentstaff_department_responsibilities_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstaff',
            name='department_office_en',
            field=models.TextField(blank=True, default='Moscow, Ordzhonikidze st, 3, cab.', null=True, verbose_name='Cabinet of the department'),
        ),
    ]
