# Generated by Django 5.2.1 on 2025-06-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_departmentstaff_department_office_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentstaff',
            name='department_office',
            field=models.TextField(blank=True, default='Москва, ул. Орджоникидзе, д. 3., каб. ', null=True, verbose_name='Кабинет департамента'),
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department_office_en',
            field=models.TextField(blank=True, default='Moscow, Ordzhonikidze st, 3, office ', null=True, verbose_name='Cabinet of the department'),
        ),
    ]
