# Generated by Django 5.0.1 on 2024-02-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_studentsapplications_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantscisnormativedocument',
            name='file',
            field=models.FileField(max_length=255, upload_to='documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='applicantsforeignnormativedocument',
            name='file',
            field=models.FileField(max_length=255, upload_to='documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='opendaysfiles',
            name='file',
            field=models.FileField(max_length=255, upload_to='documents', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='studentsapplications',
            name='file',
            field=models.FileField(max_length=255, upload_to='documents', verbose_name='Файл'),
        ),
    ]
