# Generated by Django 5.1.6 on 2025-04-29 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_studentsapplications_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantscisnormativedocument',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='applicantsforeignnormativedocument',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='opendaysfiles',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='studentsapplications',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (EN)'),
        ),
    ]
