# Generated by Django 5.2.17 on 2026-10-05 13:59

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_translations_and_options'),
        ('profiles', '0024_translations_and_options'),
        ('science', '0002_restructure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['prefix', 'name'], 'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='scientificspecialty',
            options={'ordering': ['cipher', 'name'], 'verbose_name': 'Научная специальность', 'verbose_name_plural': 'Научные специальности'},
        ),
        migrations.AddField(
            model_name='dissertationcommittee',
            name='address_ru',
            field=models.CharField(default='115419, Москва, улица Орджоникидзе, 3', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='dissertationcommittee',
            name='chairman_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Председатель'),
        ),
        migrations.AddField(
            model_name='dissertationcommittee',
            name='composition_ru',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Участник диссовета'), blank=True, null=True, size=20, verbose_name='Состав диссовета'),
        ),
        migrations.AddField(
            model_name='dissertationcommittee',
            name='deputy_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заместитель председателя'),
        ),
        migrations.AddField(
            model_name='dissertationcommittee',
            name='faculty_ru',
            field=models.CharField(default='Инженерная академия', max_length=255, null=True, verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='dissertationcommittee',
            name='organization_ru',
            field=models.CharField(default='Российский университет дружбы народов', max_length=255, null=True, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='dissertationcommittee',
            name='secretary_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Секретарь'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purpose_en',
            field=models.TextField(null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purpose_ru',
            field=models.TextField(null=True, verbose_name='Назначение'),
        ),
        migrations.AddField(
            model_name='partner',
            name='about_en',
            field=models.TextField(null=True, verbose_name='О партнёре'),
        ),
        migrations.AddField(
            model_name='partner',
            name='about_ru',
            field=models.TextField(null=True, verbose_name='О партнёре'),
        ),
        migrations.AddField(
            model_name='partner',
            name='collaboration_direction_en',
            field=models.TextField(null=True, verbose_name='Предмет сотрудничества'),
        ),
        migrations.AddField(
            model_name='partner',
            name='collaboration_direction_ru',
            field=models.TextField(null=True, verbose_name='Предмет сотрудничества'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='partner',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Наименование организации'),
        ),
        migrations.AddField(
            model_name='partner',
            name='result_en',
            field=models.TextField(null=True, verbose_name='Результат сотрудничества'),
        ),
        migrations.AddField(
            model_name='partner',
            name='result_ru',
            field=models.TextField(null=True, verbose_name='Результат сотрудничества'),
        ),
        migrations.AddField(
            model_name='scientificcenter',
            name='brief_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='scientificcenter',
            name='content_en',
            field=models.TextField(blank=True, default='', help_text='Направления деятельности, ресурсы, проекты. Если пусто — используется старый шаблон страницы.', null=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='scientificcenter',
            name='content_ru',
            field=models.TextField(blank=True, default='', help_text='Направления деятельности, ресурсы, проекты. Если пусто — используется старый шаблон страницы.', null=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='scientificcenter',
            name='field_name_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Сфера деятельности'),
        ),
        migrations.AddField(
            model_name='scientificcenter',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='scientificspecialty',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='address',
            field=models.CharField(default='115419, Москва, улица Орджоникидзе, 3', max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='address_en',
            field=models.CharField(default='115419, Москва, улица Орджоникидзе, 3', max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='chairman',
            field=models.CharField(max_length=255, verbose_name='Председатель'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='chairman_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Председатель'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='composition',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Участник диссовета'), blank=True, null=True, size=20, verbose_name='Состав диссовета'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='composition_en',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Участник диссовета'), blank=True, null=True, size=20, verbose_name='Состав диссовета'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='deputy',
            field=models.CharField(max_length=255, verbose_name='Заместитель председателя'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='deputy_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заместитель председателя'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='faculty',
            field=models.CharField(default='Инженерная академия', max_length=255, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='faculty_en',
            field=models.CharField(default='Инженерная академия', max_length=255, null=True, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='organization',
            field=models.CharField(default='Российский университет дружбы народов', max_length=255, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='organization_en',
            field=models.CharField(default='Российский университет дружбы народов', max_length=255, null=True, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='scientific_specialties',
            field=models.ManyToManyField(blank=True, related_name='committees', to='science.scientificspecialty', verbose_name='Научные специальности'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='secretary',
            field=models.CharField(max_length=255, verbose_name='Секретарь'),
        ),
        migrations.AlterField(
            model_name='dissertationcommittee',
            name='secretary_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Секретарь'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='brief_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Направления деятельности, ресурсы, проекты. Если пусто — используется старый шаблон страницы.', verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_centers', to='academy.department', verbose_name='Кафедра / департамент'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=255, verbose_name='Электронный адрес'), blank=True, null=True, size=10, verbose_name='Электронные адреса'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='field_name_en',
            field=models.TextField(blank=True, null=True, verbose_name='Сфера деятельности'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_centers', to='profiles.employeeprofile', verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть материал на сайте, не удаляя его.', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='legacy_template',
            field=models.CharField(blank=True, choices=[('neural_technologies.html', 'Нейротехнологии'), ('photon.html', 'Фотоника'), ('restoration_architectural_heritage.html', 'Реставрация архитектурного наследия'), ('subsoil_development.html', 'Разработка недр'), ('technology_and_building.html', 'Техника и технологии строительства'), ('operational_systems_and_complexes.html', 'Транспортные системы и комплексы'), ('technologies_mechanical_engineering.html', 'Машиностроение и приборостроение'), ('transfer-center.html', 'Центр трансфера технологий')], default='', help_text='Свёрстанная вручную страница центра. Используется, пока не заполнено «Подробное описание».', max_length=100, verbose_name='Старый шаблон страницы'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='scientificcenter',
            name='slug',
            field=models.CharField(blank=True, help_text='Часть адреса: /science/scientific_centers/<адрес>', max_length=100, null=True, unique=True, verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='scientificspecialty',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='scientificspecialty',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Название'),
        ),
    ]
